# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04997df51ee732805011ff69de69976bb5eb71bb86133d54f830420c53ed5e2d823eaae8a7efb22c539c58d3fc580de124530f3fe1b41db4c9ca86a93e1c2e19

test:
  secret_key_base: bc2b43f910c77540a521526dbd2677310e23aa8e912f1b614f26b4b559e2b59fbb0837e9f4b4e2d75f6a6fb1dc3518aa6aa2843a93c151dcab700d9536644cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
